import type {
  FixedStructure,
  Furniture,
  FurnitureTemplate,
  HouseholdBrief,
  Layout,
  Room,
  RoutePoint,
  WallMeasurement,
} from './types';
import { validateLayout } from './geometry';

export const APARTMENT = { width: 860, height: 550, scale: '1 cm = 1 cm' } as const;

export const DEFAULT_BRIEF: HouseholdBrief = {
  residents: 'Two adults',
  routines: 'Quiet mornings; shared dinner most evenings',
  hosting: 'Occasional dinner for four',
  workFromHome: 'One flexible desk day per week',
  accessibility: 'No current requirement',
  mustKeep: ['Owned queen bed', 'Existing kitchen plumbing'],
  minimumWalkingWidth: 72,
  budget: 1800,
  notes: 'Keep the living room open to the entry and preserve the bedroom door swing.',
  sources: [{ type: 'brief', label: 'Initial household notes' }],
};

export const ROOMS: Room[] = [
  { id: 'living', name: 'Living / dining', rect: { x: 18, y: 18, width: 502, height: 414 }, tone: 'living' },
  { id: 'kitchen', name: 'Kitchen', rect: { x: 18, y: 432, width: 340, height: 100 }, tone: 'service' },
  { id: 'bedroom', name: 'Bedroom', rect: { x: 538, y: 18, width: 304, height: 247 }, tone: 'bedroom' },
  { id: 'bathroom', name: 'Bathroom', rect: { x: 538, y: 283, width: 304, height: 137 }, tone: 'bathroom' },
  { id: 'hall', name: 'Entry hall', rect: { x: 538, y: 438, width: 304, height: 94 }, tone: 'service' },
];

export const FIXED_STRUCTURES: FixedStructure[] = [
  { id: 'wall-top', kind: 'outer-wall', name: 'North exterior wall', rect: { x: 0, y: 0, width: 860, height: 18 }, locked: true },
  { id: 'wall-left', kind: 'outer-wall', name: 'West exterior wall', rect: { x: 0, y: 0, width: 18, height: 550 }, locked: true },
  { id: 'wall-right', kind: 'outer-wall', name: 'East exterior wall', rect: { x: 842, y: 0, width: 18, height: 550 }, locked: true },
  { id: 'wall-bottom-left', kind: 'outer-wall', name: 'South living wall', rect: { x: 0, y: 532, width: 420, height: 18 }, locked: true },
  { id: 'wall-bottom-right', kind: 'outer-wall', name: 'South hall wall', rect: { x: 500, y: 532, width: 360, height: 18 }, locked: true },
  { id: 'wall-living-bedroom', kind: 'partition', name: 'Bedroom partition', rect: { x: 520, y: 0, width: 18, height: 265 }, locked: true },
  { id: 'wall-living-bath', kind: 'partition', name: 'Bathroom partition', rect: { x: 520, y: 300, width: 18, height: 132 }, locked: true },
  { id: 'wall-bedroom-bath-left', kind: 'partition', name: 'Bedroom partition left', rect: { x: 538, y: 265, width: 78, height: 18 }, locked: true },
  { id: 'wall-bedroom-bath-right', kind: 'partition', name: 'Bedroom partition right', rect: { x: 696, y: 265, width: 146, height: 18 }, locked: true },
  { id: 'wall-bath-hall-left', kind: 'partition', name: 'Bathroom threshold left', rect: { x: 538, y: 420, width: 77, height: 18 }, locked: true },
  { id: 'wall-bath-hall-right', kind: 'partition', name: 'Bathroom threshold right', rect: { x: 692, y: 420, width: 150, height: 18 }, locked: true },
  { id: 'counter', kind: 'counter', name: 'Kitchen counter', rect: { x: 18, y: 432, width: 340, height: 78 }, locked: true },
  { id: 'sink', kind: 'plumbing', name: 'Kitchen sink', rect: { x: 52, y: 444, width: 82, height: 48 }, locked: true, label: 'sink' },
  { id: 'hob', kind: 'fixture', name: 'Kitchen hob', rect: { x: 188, y: 444, width: 72, height: 48 }, locked: true, label: 'hob' },
  { id: 'bath-sink', kind: 'plumbing', name: 'Bathroom sink', rect: { x: 563, y: 298, width: 82, height: 52 }, locked: true, label: 'sink' },
  { id: 'bath-shower', kind: 'fixture', name: 'Shower', rect: { x: 741, y: 296, width: 84, height: 108 }, locked: true, label: 'shower' },
  { id: 'bath-toilet', kind: 'fixture', name: 'Toilet', rect: { x: 654, y: 323, width: 62, height: 78 }, locked: true, label: 'toilet' },
  { id: 'entry-swing', kind: 'door', name: 'Entry door swing', rect: { x: 420, y: 462, width: 80, height: 70 }, locked: true },
  { id: 'bedroom-swing', kind: 'door', name: 'Bedroom door swing', rect: { x: 616, y: 265, width: 80, height: 78 }, locked: true },
  { id: 'bath-swing', kind: 'door', name: 'Bathroom door swing', rect: { x: 615, y: 350, width: 78, height: 70 }, locked: true },
  { id: 'window-north-living', kind: 'window', name: 'Living room window', rect: { x: 112, y: 0, width: 122, height: 18 }, locked: true },
  { id: 'window-north-bed', kind: 'window', name: 'Bedroom window', rect: { x: 650, y: 0, width: 122, height: 18 }, locked: true },
  { id: 'window-west', kind: 'window', name: 'Living room side window', rect: { x: 0, y: 100, width: 18, height: 110 }, locked: true },
  { id: 'opening-entry', kind: 'opening', name: 'Entry opening', rect: { x: 420, y: 520, width: 80, height: 30 }, locked: true },
];

export const ROUTE_POINTS: RoutePoint[] = [
  { id: 'entry', name: 'Entry', position: { x: 460, y: 450 }, room: 'Entry hall' },
  { id: 'sofa', name: 'Sofa', position: { x: 350, y: 190 }, room: 'Living / dining' },
  { id: 'dining', name: 'Dining', position: { x: 110, y: 330 }, room: 'Living / dining' },
  { id: 'desk', name: 'Desk', position: { x: 55, y: 170 }, room: 'Living / dining' },
  { id: 'bed', name: 'Bed', position: { x: 744, y: 140 }, room: 'Bedroom' },
  { id: 'bathroom', name: 'Bathroom', position: { x: 705, y: 345 }, room: 'Bathroom' },
];

export const INITIAL_WALL_MEASUREMENTS: WallMeasurement[] = [
  { wallId: 'wall-top', name: 'North exterior wall', lengthCm: APARTMENT.width },
];

const template = (
  item: Omit<FurnitureTemplate, 'id' | 'defaultPosition' | 'defaultRotation'> & { id: string; defaultPosition: { x: number; y: number }; defaultRotation?: number },
): FurnitureTemplate => item;

export const FURNITURE_CATALOGUE: FurnitureTemplate[] = [
  template({
    id: 'sofa',
    catalogueId: 'sofa',
    name: 'Sofa',
    kind: 'sofa',
    width: 200,
    depth: 90,
    defaultPosition: { x: 350, y: 190 },
    defaultRotation: 90,
    clearance: { front: 20, back: 15, left: 10, right: 10 },
    cost: 0,
    ownership: 'owned',
    custom: false,
    color: '#e9e7e1',
    description: 'Owned three-seat sofa',
  }),
  template({
    id: 'desk',
    catalogueId: 'desk',
    name: 'Desk',
    kind: 'desk',
    width: 120,
    depth: 60,
    defaultPosition: { x: 55, y: 170 },
    defaultRotation: 90,
    clearance: { front: 60, back: 10, left: 10, right: 10 },
    cost: 0,
    ownership: 'owned',
    custom: false,
    color: '#edecea',
    description: 'Compact work desk',
  }),
  template({
    id: 'dining-table',
    catalogueId: 'dining-table',
    name: 'Dining table',
    kind: 'dining-table',
    width: 140,
    depth: 80,
    defaultPosition: { x: 110, y: 330 },
    clearance: { front: 45, back: 45, left: 45, right: 45 },
    cost: 0,
    ownership: 'owned',
    custom: false,
    color: '#eeece6',
    description: 'Owned table with four chairs',
  }),
  template({
    id: 'queen-bed',
    catalogueId: 'queen-bed',
    name: 'Queen bed',
    kind: 'queen-bed',
    width: 160,
    depth: 200,
    defaultPosition: { x: 720, y: 140 },
    clearance: { front: 60, back: 20, left: 45, right: 45 },
    cost: 0,
    ownership: 'owned',
    custom: false,
    color: '#ebe9e4',
    description: 'Owned queen bed',
  }),
  template({
    id: 'bookshelf',
    catalogueId: 'bookshelf',
    name: 'Bookshelf',
    kind: 'bookshelf',
    width: 120,
    depth: 30,
    defaultPosition: { x: 565, y: 130 },
    defaultRotation: 90,
    clearance: { front: 35, back: 5, left: 5, right: 5 },
    cost: 0,
    ownership: 'owned',
    custom: false,
    color: '#f0eee8',
    description: 'Owned low bookshelf',
  }),
  template({
    id: 'dining-chair',
    catalogueId: 'dining-chair',
    name: 'Dining chair',
    kind: 'dining-chair',
    width: 40,
    depth: 42,
    defaultPosition: { x: 190, y: 262 },
    clearance: { front: 35, back: 15, left: 10, right: 10 },
    cost: 0,
    ownership: 'owned',
    custom: false,
    color: '#f1efe9',
    description: 'Owned dining chair',
  }),
  template({
    id: 'armchair',
    catalogueId: 'armchair',
    name: 'Armchair',
    kind: 'armchair',
    width: 82,
    depth: 82,
    defaultPosition: { x: 285, y: 220 },
    clearance: { front: 45, back: 10, left: 15, right: 15 },
    cost: 320,
    ownership: 'buy',
    custom: false,
    color: '#eeeae1',
    description: 'Reading chair',
  }),
  template({
    id: 'coffee-table',
    catalogueId: 'coffee-table',
    name: 'Coffee table',
    kind: 'coffee-table',
    width: 100,
    depth: 55,
    defaultPosition: { x: 275, y: 195 },
    clearance: { front: 45, back: 45, left: 45, right: 45 },
    cost: 140,
    ownership: 'buy',
    custom: false,
    color: '#f0eee9',
    description: 'Low rectangular coffee table',
  }),
  template({
    id: 'side-table',
    catalogueId: 'side-table',
    name: 'Side table',
    kind: 'side-table',
    width: 45,
    depth: 45,
    defaultPosition: { x: 465, y: 255 },
    clearance: { front: 25, back: 25, left: 25, right: 25 },
    cost: 90,
    ownership: 'buy',
    custom: false,
    color: '#f1efe9',
    description: 'Small occasional table',
  }),
  template({
    id: 'dresser',
    catalogueId: 'dresser',
    name: 'Dresser',
    kind: 'dresser',
    width: 110,
    depth: 48,
    defaultPosition: { x: 700, y: 235 },
    clearance: { front: 70, back: 10, left: 10, right: 10 },
    cost: 240,
    ownership: 'buy',
    custom: false,
    color: '#eceae4',
    description: 'Six-drawer dresser',
  }),
  template({
    id: 'wardrobe',
    catalogueId: 'wardrobe',
    name: 'Wardrobe',
    kind: 'wardrobe',
    width: 120,
    depth: 60,
    defaultPosition: { x: 650, y: 485 },
    clearance: { front: 75, back: 10, left: 10, right: 10 },
    cost: 480,
    ownership: 'buy',
    custom: false,
    color: '#e9e8e2',
    description: 'Tall storage wardrobe',
  }),
  template({
    id: 'floor-lamp',
    catalogueId: 'floor-lamp',
    name: 'Floor lamp',
    kind: 'floor-lamp',
    width: 35,
    depth: 35,
    defaultPosition: { x: 330, y: 110 },
    clearance: { front: 20, back: 10, left: 10, right: 10 },
    cost: 75,
    ownership: 'buy',
    custom: false,
    color: '#f2f0e8',
    description: 'Slim floor lamp',
  }),
  template({
    id: 'plant',
    catalogueId: 'plant',
    name: 'Plant',
    kind: 'plant',
    width: 45,
    depth: 45,
    defaultPosition: { x: 55, y: 55 },
    clearance: { front: 15, back: 5, left: 5, right: 5 },
    cost: 35,
    ownership: 'buy',
    custom: false,
    color: '#f0eee7',
    description: 'Medium floor plant',
  }),
  template({
    id: 'rug',
    catalogueId: 'rug',
    name: 'Area rug',
    kind: 'rug',
    width: 240,
    depth: 160,
    defaultPosition: { x: 280, y: 220 },
    clearance: { front: 0, back: 0, left: 0, right: 0 },
    cost: 280,
    ownership: 'buy',
    custom: false,
    color: '#f2f0ea',
    description: 'Large living room rug',
  }),
];

const makeFurniture = (templateItem: FurnitureTemplate, id: string, overrides: Partial<Furniture> = {}): Furniture => ({
  id,
  catalogueId: templateItem.catalogueId,
  name: templateItem.name,
  kind: templateItem.kind,
  width: templateItem.width,
  depth: templateItem.depth,
  position: templateItem.defaultPosition,
  rotation: templateItem.defaultRotation ?? 0,
  clearance: templateItem.clearance,
  cost: templateItem.cost,
  ownership: templateItem.ownership,
  locked: false,
  dimensionStatus: 'confirmed',
  custom: templateItem.custom,
  color: templateItem.color,
  ...overrides,
});

export const INITIAL_FURNITURE: Furniture[] = [
  makeFurniture(FURNITURE_CATALOGUE[0], 'furn-sofa', { dimensionStatus: 'confirmed' }),
  makeFurniture(FURNITURE_CATALOGUE[1], 'furn-desk'),
  makeFurniture(FURNITURE_CATALOGUE[2], 'furn-dining-table'),
  makeFurniture(FURNITURE_CATALOGUE[3], 'furn-queen-bed', { locked: true, position: { x: 744, y: 140 } }),
  makeFurniture(FURNITURE_CATALOGUE[4], 'furn-bookshelf', { dimensionStatus: 'estimated' }),
  makeFurniture(FURNITURE_CATALOGUE[5], 'furn-chair-north', { position: { x: 110, y: 262 } }),
  makeFurniture(FURNITURE_CATALOGUE[5], 'furn-chair-south', { position: { x: 110, y: 398 }, rotation: 180 }),
  makeFurniture(FURNITURE_CATALOGUE[5], 'furn-chair-west', { position: { x: 50, y: 330 }, rotation: 270 }),
  makeFurniture(FURNITURE_CATALOGUE[5], 'furn-chair-east', { position: { x: 195, y: 330 }, rotation: 90 }),
];

export const INITIAL_LAYOUT: Layout = {
  id: 'layout-a',
  name: 'Layout A',
  createdAt: '2026-09-02T12:00:00.000Z',
  furniture: INITIAL_FURNITURE,
  routeCheck: { startId: 'entry', endId: 'sofa', minimumWidth: DEFAULT_BRIEF.minimumWalkingWidth },
};

export function seededValidation(layout: Layout, brief = DEFAULT_BRIEF) {
  return validateLayout(
    layout.furniture,
    FIXED_STRUCTURES,
    ROUTE_POINTS,
    brief,
    layout.routeCheck,
    APARTMENT,
  );
}
